### Health check
GET http://localhost:8080/actuator/health
Accept: application/vnd.spring-boot.actuator.v3+json

### Create course
< {%
const id = $random.uuid
client.global.set("courseId", id)
%}
POST http://localhost:8080/course
Content-Type: application/json

{
  "id": "{{courseId}}",
  "name": "{{$random.educator.course}}"
}

### Get course by ID
GET http://localhost:8080/course/{{courseId}}