spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRESQL_URL:localhost}:${POSTGRESQL_PORT:5432}/course_database"
    username: course_username
    password: ${POSTGRESQL_PASSWORD:course_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
